<label><strong><?php echo $this->__('Linked Accounts'); ?></strong></label>
<?php if($this->hasSavedDetails()): ?>

    <p><?php echo $this->__('The customer has the following linked PayPal accounts.'); ?></p>
    <table width="100%" cellspacing="0" cellpadding="0" id="paypal-saved-accounts">
        <tbody>
        <?php
        $count = 0;
        foreach($this->getSavedDetails() as $savedDetail):
            ?>
            <tr valign="middle">
                <td width="20"><input type="radio" name="payment[paypal_payment_method_token]" id="<?php echo $savedDetail->token; ?>" value="<?php echo $savedDetail->token; ?>"<?php echo ($count == 0 ? ' checked="checked"' : ''); ?>/></td>
                <td valign="middle">
                    <label for="<?php echo $savedDetail->token; ?>" style="line-height: 48px;">
                        <img src="<?php echo $this->getSkinUrl('images/gene/braintree/PP.png') ?>" align="left" />
                        <span class="saved-paypal-email"><?php echo $savedDetail->email; ?></span>
                    </label>
                </td>
            </tr>
            <?php
            ++$count;
        endforeach; ?>
        </tbody>
    </table>

<?php else: ?>
    <p><?php echo $this->__('This customer has not linked any PayPal accounts with your Magento store. Customers are only able to link PayPal accounts through the front-end checkout of your store.'); ?></p>
<?php endif; ?>
