<?php
/**
 * Add in support for FME Quick Checkout
 * https://www.fmeextensions.com/one-step-checkout.html
 * @author Dave Macaulay <braintreesupport@gene.co.uk>
 */
?>
<!-- FME QUCKCHECKOUT BRAINTREE SUPPORT -->
<script type="text/javascript">

    vZeroIntegration.addMethods({

        /**
         * Validate the entire checkout
         */
        validateAll: function() {
            var validation = new Validation(review.form);
            return validation.validate();
        },

        /**
         * Hook into the checkouts loading states
         */
        setLoading: function () {
            return onestepcheckout.setLoadWaitingReview('saving_order');
        },
        resetLoading: function () {
            return onestepcheckout.setLoadWaitingPayment(false);
        },

        /**
         * Capture the original submit function
         */
        captureOriginalSubmitFn: function () {
            this._originalSubmitFn = Review.prototype.save;
            return true;
        },

        /**
         * Attach an observer to the submit action of the checkout to tokenize the card details
         */
        prepareSubmitObserver: function() {

            // Store a pointer to the vZero integration
            var vzeroIntegration = this;

            // Re-define the original method so we can do some jazz with it
            Review.prototype.save = function () {

                if (vzeroIntegration.shouldInterceptSubmit('creditcard')) {

                    // Store a pointer to the payment class
                    var paymentThis = this;
                    var paymentArguments = arguments;

                    // If everything was a success on the checkout end, let's submit the vZero integration
                    vzeroIntegration.submit('creditcard', function () {
                        return vzeroIntegration._originalSubmitFn.apply(paymentThis, paymentArguments);
                    });

                } else {
                    // If not run the original code
                    return vzeroIntegration._originalSubmitFn.apply(this, arguments);
                }

            };

        },

        /**
         * The action to run after the PayPal action has been completed
         */
        submitCheckout: function() {
            // Run the original checkouts submit action
            return review.save();
        }

    });

    /**
     * Start a new instance of our integration
     *
     * @type {vZeroIntegration}
     */
    new vZeroIntegration(
        (window.vzero || false),
        (window.vzeroPaypal || false),
        '<div id="paypal-complete"><div id="paypal-container"></div></div>',
        '#review-buttons-container .input_button',
        true,
        {
            ignoreAjax: ['checkout/onestep/saveOrder']
        }
    );

</script>