<?php
/**
 * Add in support for Magestore One Step Checkout
 * http://ecommerce.aheadworks.com/magento-extensions/one-step-checkout.html
 * @author Dave Macaulay <braintreesupport@gene.co.uk>
 */
?>
<!-- MAGESTORE BRAINTREE SUPPORT -->
<script type="text/javascript">

    vZeroIntegration.addMethods({

        /**
         * Validate the entire checkout
         */
        validateAll: function() {
            var validator = new Validation('one-step-checkout-form');
            return validator.validate();
        },

        /**
         * Return the payment method from the checkouts methods
         */
        getPaymentMethod: function() {
            return $RF($('one-step-checkout-form'), 'payment[method]');
        },

        /**
         * Activate the loading state of this checkout
         */
        setLoading: function() {
            $('onestepcheckout-button-place-order').removeClassName('onestepcheckout-btn-checkout');
            $('onestepcheckout-button-place-order').addClassName('place-order-loader');
            already_placing_order = true;
        },

        /**
         * Reset the loading state of the checkout
         */
        resetLoading: function() {
            $('onestepcheckout-button-place-order').addClassName('onestepcheckout-btn-checkout');
            $('onestepcheckout-button-place-order').removeClassName('place-order-loader');
            already_placing_order = false;
        },

        /**
         * Show the placing order div before the submit
         */
        beforeSubmit: function(callback) {
            $('onestepcheckout-place-order-loading').show();
            return this._beforeSubmit(callback);
        },
        afterSubmit: function() {
            $('onestepcheckout-place-order-loading').hide();
        },

        /**
         * Capture the original submit function
         */
        captureOriginalSubmitFn: function () {
            this._originalSubmitFn = oscPlaceOrder;
            return true;
        },

        /**
         * Attach an observer to the submit action of the checkout to tokenize the card details
         */
        prepareSubmitObserver: function() {

            // Store a pointer to the vZero integration
            var vzeroIntegration = this;

            // Re-define the original method so we can do some jazz with it
            oscPlaceOrder = function (element) {

                if (vzeroIntegration.shouldInterceptSubmit('creditcard')) {

                    // Store a pointer to the payment class
                    var paymentThis = this;
                    var paymentArguments = arguments;

                    // If everything was a success on the checkout end, let's submit the vZero integration
                    vzeroIntegration.submit('creditcard', function () {
                        return vzeroIntegration._originalSubmitFn.apply(paymentThis, paymentArguments);
                    });

                } else {
                    // If not run the original code
                    return vzeroIntegration._originalSubmitFn.apply(this, arguments);
                }

            };
        },

        /**
         * Prepare an event to insert the PayPal button in place of the complete checkout button
         */
        preparePaymentMethodSwitchObserver: function() {
            // Store a pointer to the vZero integration
            var vzeroIntegration = this;

            // Intercept people swapping methods
            var _originalSaveShippingMethod = save_shipping_method;
            save_shipping_method = function (shipping_method_url, update_shipping_payment, update_shipping_review) {

                // Run our method switch function
                vzeroIntegration.paymentMethodSwitch();

                // Run the original function
                return _originalSaveShippingMethod.apply(this, arguments);
            };
        },

        /**
         * The action to run after the PayPal action has been completed
         */
        submitCheckout: function() {
            return oscPlaceOrder($('onestepcheckout-button-place-order'));
        }

    });

    /**
     * Start a new instance of our integration
     *
     * @type {vZeroIntegration}
     */
    new vZeroIntegration(
        (window.vzero || false),
        (window.vzeroPaypal || false),
        '<div id="paypal-complete"><div id="paypal-container"></div></div>',
        '#onestepcheckout-button-place-order',
        true
    );

</script>