<?php
/**
 * Add in support for Oye One Step Checkout
 * http://oyenetwork.com/products/advanced-checkout.html
 * @author Dave Macaulay <braintreesupport@gene.co.uk>
 */
?>
<!-- OYE BRAINTREE SUPPORT -->
<script type="text/javascript">
    vZeroIntegration.addMethods({

        /**
         * Validate the entire checkout
         * Annoyingly IWD hasn't already wrapped this in a function
         */
        validateAll: function() {
            return checkout.validateCheckout();
        },

        setLoading: function() {
            checkout.setLoadWaiting();
        },

        resetLoading: function() {
            checkout.resetLoadWaiting();
        },

        /**
         * Capture the original submit function
         */
        captureOriginalSubmitFn: function () {
            this._originalSubmitFn = Checkout.prototype.saveOrder;
            this._originalUpdateContents = Checkout.prototype.updateContents;
            return true;
        },

        /**
         * Attach an observer to the submit action of the checkout to tokenize the card details
         */
        prepareSubmitObserver: function() {

            // Store a pointer to the vZero integration
            var vzeroIntegration = this;

            // Re-define the original method so we can do some jazz with it
            Checkout.prototype.saveOrder = function () {

                if (vzeroIntegration.shouldInterceptSubmit('creditcard')) {

                    // Store a pointer to the payment class
                    var paymentThis = this;
                    var paymentArguments = arguments;

                    // If everything was a success on the checkout end, let's submit the vZero integration
                    vzeroIntegration.submit('creditcard', function () {
                        return vzeroIntegration._originalSubmitFn.apply(paymentThis, paymentArguments);
                    });

                } else {
                    // If not run the original code
                    return vzeroIntegration._originalSubmitFn.apply(this, arguments);
                }

            };

            // Disable the save action, so the checkout doesn't submit multiple times
            Review.prototype.save = function() { return false; };

            // Fix the system that updates the contents
            Checkout.prototype.updateContents =  function(contents, updateError){

                var response = vzeroIntegration._originalUpdateContents.apply(this, arguments);

                // Only run these functions if we're updating the review block
                if (typeof contents.blocks == 'object' && 'review' in contents.blocks) {

                    // The Ajax request might kill our events
                    if (vzeroIntegration.isOnepage) {
                        vzeroIntegration.initSavedPayPal();
                        vzeroIntegration.rebuildPayPalButton();
                        vzeroIntegration.checkSavedOther();

                        // If hosted fields is enabled init the environment
                        if (vzeroIntegration.vzero.hostedFields) {
                            vzeroIntegration.initHostedFields();
                        }
                    }

                    // Make sure we're observing the saved methods correctly
                    vzeroIntegration.initSavedMethods();
                }

                return response;

            };

        },

        /**
         * Return the correct payment method
         */
        getPaymentMethod: function() {
            // I'm buying these developers a dictionary
            return checkout._paymentInstace.currentMethod;
        },

        /**
         * The action to run after the PayPal action has been completed
         */
        submitCheckout: function() {
            // Run the original checkouts submit action
            return checkout.saveOrder();
        }

    });

    /**
     * Start a new instance of our integration
     *
     * @type {vZeroIntegration}
     */
    var integration = new vZeroIntegration(
        (window.vzero || false),
        (window.vzeroPaypal || false),
        '<div id="paypal-complete"><div id="paypal-container"></div></div>',
        '#review-buttons-container .btn-checkout',
        true,
        {
            ignoreAjax: ['checkout/onepage/saveOrder']
        }
    );

</script>