<?php
/* @var Gene_Braintree_Block_Applepay_Info $this */
?>
<div class="braintree-applepay" style="background: white;padding: 9px 16px;border-radius:5px;margin: 0 0 8px 0;box-shadow: 0 0 7px rgba(0,0,0,0.15);">
    <div id="braintree_creditcard_logo" style="padding-top: 5px;padding-left: 2px;">
        <img src="/skin/frontend/base/default/images/gene/braintree/apple-pay-logo.png" width="100" alt="<?php echo $this->__('Apple Pay - Braintree'); ?>" /> by
        <a href="http://gene.co.uk" rel="noopener" target="_blank" style="text-decoration: none;color: black;">Gene Commerce</a>
    </div>

    <?php if ($_specificInfo = $this->getSpecificInformation()):?>
        <table>
            <?php foreach ($_specificInfo as $_label => $_value):?>
                <tr>
                    <th width="220"><?php echo $this->escapeHtml($_label)?>:</td>
                    <td><?php echo nl2br(implode($this->getValueAsArray($_value, false), "\n"))?></td>
                </tr>
            <?php endforeach; ?>
        </table>
    <?php endif;?>

    <?php if (!$this->isSingleInvoice()): ?>
        <p><?php echo $this->__('This order contains multiple Braintree transactions, to view more information on each transaction please view their corresponding invoice.'); ?></p>
    <?php endif; ?>
</div>

<?php echo $this->getChildHtml()?>