<?php
/* @var $this Gene_Braintree_Block_Googlepay */
?>
<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display: none;">
    <div class="googlepay-info">
        <img src="<?php echo $this->getSkinUrl('images/gene/braintree/google-pay-logo.png'); ?>" width="100" style="margin: 10px 0;" />
        <p><?php echo $this->__('You will be presented with Google Pay at the end of the checkout process.'); ?></p>
        <input type="hidden" name="payment[payment_method_nonce]" id="googlepay-payment-nonce" />
    </div>
</div>

<script type="text/javascript">
    if (typeof vzero !== 'undefined') {
        // Always set the amount as it's needed within 3D secure requests
        vzero.setAmount('<?php echo Mage::helper('gene_braintree')->formatPrice(Mage::getSingleton('checkout/cart')->getQuote()->collectTotals()->getGrandTotal()); ?>');
    }
</script>
