<?php
/* @var $this Gene_Braintree_Block_Express_Checkout */
?>
<form action="<?php echo $this->getUrl('braintree/express/shipping') ?>" method="post" id="gene_braintree_paypal_express_pp">
    <input type="hidden" name="submit_shipping" value="1" />

    <div class="item-row"><strong><?php echo $this->__('Your Order'); ?></strong></div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

    <?php foreach($this->getQuote()->getAllVisibleItems() as $item): ?>
        <div class="product-row item-row">
            <div class="product-image"><img src="<?php echo Mage::helper('catalog/image')->init($item->getProduct(), 'thumbnail'); ?>" /></div>
            <div class="product-info">
                <h2 class="product-name"><?php echo $item->getProduct()->getName(); ?></h2>
                <div class="product-qty"><?php echo $this->__('Quantity:'); ?> <?php echo $item->getQty(); ?></div>
            </div>
        </div>
    <?php endforeach; ?>

    <?php if ($this->hasShippingRates()): ?>
        <div class="shipping-row item-row">
            <strong><?php echo $this->__('Shipping method:'); ?></strong>
            <?php foreach($this->getShippingRates() as $_rate): ?>
                <label class="item-subrow">
                    <input type="radio" name="shipping_method" value="<?php echo $_rate->getCode(); ?>" onchange="ppExpress.updateShipping('<?php echo $_rate->getCode(); ?>')" />

                    <?php echo $_rate->getMethodTitle(); ?> &#8211;
                    <strong><?php echo Mage::helper('core')->currency($_rate->getPrice(), true, false); ?></strong>
                </label>
            <?php endforeach; ?>
        </div>
        <div class="coupon-row item-row">
            <div id="paypal-express-coupon-error" class="error" style="display: none;"></div>
            <input type="text" name="coupon" id="paypal-express-coupon" placeholder="<?php echo $this->__('Coupon Code'); ?>" />
            <button type="button" name="coupon-apply" id="paypal-express-coupon-apply" class="coupon-submit button" onclick="return ppExpress.updateCoupon();"><?php echo $this->__('Apply Coupon'); ?></button>
            <button type="button" name="coupon-remove" id="paypal-express-coupon-remove" class="coupon-submit button" onclick="return ppExpress.removeCoupon();" style="display: none;"><?php echo $this->__('Remove Coupon'); ?></button>
        </div>
        <div class="item-row" id="paypal-express-totals">
            <?php echo $this->getChildHtml('totals'); ?>
        </div>

        <button type="submit" class="button" id="paypal-express-submit"><?php echo $this->__('Place Order'); ?></button>
    <?php else: ?>
        <p><?php echo $this->__('There are no shipping methods available for your address.'); ?></p>
        <p><?php echo $this->__('Please repeat the process, selecting an address that we\'re able to deliver to.'); ?></p>
        <br /><br />
    <?php endif; ?>

    <div><button type="button" class="button2" onclick="ppExpress.hideModal();"><?php echo $this->__('Cancel'); ?></button></div>
</form>